### ISSUE TITLE
Datei wurde nicht gefunden

### ISSUE THREAD

**Issue by solala888** [hmmh/typo3-solr-file-indexer#10]
Guten Tag,

ich habe das Plugin auf meinen Lokal installiert und eingerichtet. Typo3 Plugin "solr" funktioniert immer noch, "tika" und "filemetadata" laufen auch gut. Aber die Datei wurde leider nicht gefunden... Muss ich "solrfal" auch installieren?

Anbei den Infos meiner Lokalumgebung:
Typo3 8.7.24
solr 8.1.2
tika 3.1.1
filemetadata 8.7.24
solr_file_indexer 1.3.0

System läuft unter Docker.

Könnten Sie bitte mir helfen? Vielen Dank & beste Grüße!

**Comment by swilking** [comment]
Hallo,

solrfal wird nicht benötigt. Die EXT:tika ist für solr_file_indexer optional. In der Extension-Konfiguration von solr_file_indexer kann gewählt werden, ob die EXT:tika verwendet werden soll oder nicht. Wichtig ist auch, dass das TypoScript eingebunden ist, da dort die Settings für die Datensätze für plugin tx_solr.index.queue definiert sind.

In der Filelist muss das Dokument einmal ausgewählt werden und dort dem Suchindex hinzugefügt werden. Dann sollte es automatisch in die IndexQueue von Solr aufgenommen werden und bei der Indexierung dem Solr-Core hinzugefügt werden.

Ggf. kann es auch helfen, über den Solr-Adminpanel <HOST>/solr/admin direkt in dem Core zu prüfen, ob das Dokument dort vorhanden ist.

Ich hoffe, ich konnte Ihnen weiterhelfen.

Freundliche Grüße,
Sascha Wilking

Von: Lu, Feng <notifications@github.com>
Gesendet: Dienstag, 5. Februar 2019 11:58
An: hmmh/typo3-solr-file-indexer <typo3-solr-file-indexer@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hmmh/typo3-solr-file-indexer] Datei wurde nicht gefunden (#10)


Guten Tag,

ich habe das Plugin auf meinen Lokal installiert und eingerichtet. Typo3 Plugin "solr" funktioniert immer noch, "tika" und "filemetadata" laufen auch gut. Aber die Datei wurde leider nicht gefunden... Muss ich "solrfal" auch installieren?

Anbei den Infos meiner Lokalumgebung:
Typo3 8.7.24
solr 8.1.2
tika 3.1.1
filemetadata 8.7.24
solr_file_indexer 1.3.0

System läuft unter Docker.

Könnten Sie bitte mir helfen? Vielen Dank & beste Grüße!

**Comment by solala888** [comment]
Hallo,

vielen Dank für die blitzschnelle Antwort!

Ich habe Ihr Beispiel-TypoScript in meinem System hinterlegt. Es scheint die Initialisierung läuft ( siehe Screenhot von Tabelle "tx_solr_indexqueue_item" )

<img width="1080" alt="bildschirmfoto 2019-02-06 um 09 28 59" src="https://user-images.githubusercontent.com/8091377/52329451-148baa80-29f3-11e9-9ba4-359363c98376.png">

Anbei noch ein Screeshot von Solr

<img width="1375" alt="bildschirmfoto 2019-02-06 um 09 41 11" src="https://user-images.githubusercontent.com/8091377/52329679-b1e6de80-29f3-11e9-939d-c139cd6c0095.png">

Wahrscheinlich sollte ich die TypoScript Konfiguration ändern?

Beste Grüße
Feng Lu

**Comment by swilking** [comment]
Hallo,

die Konfiguration kann nach Belieben geändert werden. Im Solr-Admin kann man im Core Selector den richtigen Core auswählen, dann erhält man eine Übersicht über alle indexierten Elemente. Dort kann auch eine Suche durchgeführt werden.

Freundliche Grüße,
Sascha Wilking

Von: Lu, Feng <notifications@github.com>
Gesendet: Mittwoch, 6. Februar 2019 09:55
An: hmmh/typo3-solr-file-indexer <typo3-solr-file-indexer@noreply.github.com>
Cc: Sascha Wilking <Sascha.Wilking@hmmh.de>; Comment <comment@noreply.github.com>
Betreff: Re: [hmmh/typo3-solr-file-indexer] Datei wurde nicht gefunden (#10)


Hallo,

vielen Dank für die blitzschnelle Antwort!

Ich habe Ihr Beispiel-TypoScript in meinem System hinterlegt. Es scheint die Initialisierung läuft ( siehe Screenhot von Tabelle "tx_solr_indexqueue_item" )

[Das Bild wurde vom Absender entfernt. bildschirmfoto 2019-02-06 um 09 28 59]<https://user-images.githubusercontent.com/8091377/52329451-148baa80-29f3-11e9-9ba4-359363c98376.png>

Anbei noch ein Screeshot von Solr

[Das Bild wurde vom Absender entfernt. bildschirmfoto 2019-02-06 um 09 41 11]<https://user-images.githubusercontent.com/8091377/52329679-b1e6de80-29f3-11e9-939d-c139cd6c0095.png>

Wahrscheinlich sollte ich die TypoScript Konfiguration ändern?

Beste Grüße
Feng Lu

**Comment by solala888** [comment]
Hallo,

ich möchte eine Datei indexieren, und hab im System so eingerichtet:

<img width="672" alt="bildschirmfoto 2019-02-06 um 13 36 14" src="https://user-images.githubusercontent.com/8091377/52342274-4281e680-2a15-11e9-9c94-e151448afcc8.png">

<img width="569" alt="bildschirmfoto 2019-02-06 um 13 36 31" src="https://user-images.githubusercontent.com/8091377/52342282-46156d80-2a15-11e9-8f2a-2348fef8306d.png">

Aber findet Solr trotzdem nicht.

<img width="965" alt="bildschirmfoto 2019-02-06 um 13 41 00" src="https://user-images.githubusercontent.com/8091377/52342378-88d74580-2a15-11e9-8260-c0bf611c1e84.png">

Ich habe auch komplett neu indexiert... Hätten Sie vielleicht noch eine Idee?

Beste Grüße
Feng Lu

**Comment by swilking** [comment]
Hallo,

wenn das Dokument im Suchindex war und indexiert wurde prüfen Sie bitte, ob es eine Fehlermeldung bei der Indexierung für einen sys_file_metadata Eintrag gab. Suchen Sie ggf. auch einmal nach einem Begriff, der innerhalb des Dokuments vorkommt. Versuchen Sie testweise einmal andere Dokumente zu indexieren und suchen Sie nach Begriffen, die in den Dokumenten vorkommen.

Suchen Sie im Solr-Admin zusätzlich einmal nach alle Typen sys_file_metadata, so werden alle indexierten Dokumente zurückgegeben. So können Sie auf jeden Fall sicherstellen, ob das Dokument überhaupt im Suchindex gelandet ist.

[cid:image005.png@01D4BE26.A7291870]

Um welche Art Dokumente handelt es sich (PDF, DOC etc)? Stellen Sie bitte sicher, das sich der Filetype in der TypoScript-Konfiguration unter allowedFileTypes befindet. Im Standardsetup sind dieses pdf, doc, docx und xlsx.

Arbeiten Sie ggf. mit Lokalisierungen (z.B. Default Englisch, ID1 Deutsch)? Dann muss das Dokument auch in der entsprechenden Sprache vorhanden sein bzw. in der Extension-Konfiguration muss ignoreLocalization aktiviert werden.

Freundliche Grüße,
Sascha Wilking



Von: Lu, Feng <notifications@github.com>
Gesendet: Mittwoch, 6. Februar 2019 13:50
An: hmmh/typo3-solr-file-indexer <typo3-solr-file-indexer@noreply.github.com>
Cc: Sascha Wilking <Sascha.Wilking@hmmh.de>; Comment <comment@noreply.github.com>
Betreff: Re: [hmmh/typo3-solr-file-indexer] Datei wurde nicht gefunden (#10)


Hallo,

ich möchte eine Datei indexieren, und hab im System so eingerichtet:

[Das Bild wurde vom Absender entfernt. bildschirmfoto 2019-02-06 um 13 36 14]<https://user-images.githubusercontent.com/8091377/52342274-4281e680-2a15-11e9-9c94-e151448afcc8.png>

[Das Bild wurde vom Absender entfernt. bildschirmfoto 2019-02-06 um 13 36 31]<https://user-images.githubusercontent.com/8091377/52342282-46156d80-2a15-11e9-8f2a-2348fef8306d.png>

Aber findet Solr trotzdem nicht.

[Das Bild wurde vom Absender entfernt. bildschirmfoto 2019-02-06 um 13 41 00]<https://user-images.githubusercontent.com/8091377/52342378-88d74580-2a15-11e9-8260-c0bf611c1e84.png>

Ich habe auch komplett neu indexiert... Hätten Sie vielleicht noch eine Idee?

Beste Grüße
Feng Lu

**Comment by swilking** [comment]
is no issue
