### ISSUE TITLE
Error with ApacheSolrForTypo3\Solr\Site

### ISSUE THREAD

**Issue by TeddyBears** [hmmh/typo3-solr-file-indexer#12]
Hello
i installed the following element

- TYPO3 v9.5.4
- solr v9.0.1
- solr_file_indexer v2.0.0

I create a scheduler task (Extbase CommandController) to index files. when i launch the task i get this error

`Argument 1 passed to HMMH\SolrFileIndexer\Service\Adapter\SolrConnection::getConnectionsBySite() must be an instance of ApacheSolrForTypo3\Solr\Site, instance of ApacheSolrForTypo3\Solr\Domain\Site\Site given, called in /var/www/sites/pprod.cibtp.fr/web/typo3conf/ext/solr_file_indexer/Classes/Command/SolrCommandController.php`

In Sorl extension the 'ApacheSolrForTypo3\Solr\Site' is deprecated. If i change it to `ApacheSolrForTypo3\Solr\Domain\Site\Site` into `HMMH\SolrFileIndexer\Service\Adapter\SolrConnection` in line 29 i don't have the error anymore

**Comment by swilking** [comment]
Hello,
it looks you have a mix of different versions of the solr_file_indexer extension. Since version 2.0 the Extbase SolrCommandController was replaced by a scheduler task. And also the file `HMMH\SolrFileIndexer\Service\Adapter\SolrConnection` does not exist anymore in this version.
