### ISSUE TITLE
[HY000][1364] Field 'errors' doesn't have a default value

### ISSUE THREAD

**Issue by epxfrho** [hmmh/typo3-solr-file-indexer#13]
We have an issue when the extension inserts data into tx_solr_indexqueue_item.

typo3 8.7.27
solr_file_indexer 1.3.2
solr 8.1.2

Typo3 error message:
`An exception occurred while executing 'INSERT INTO tx_solr_indexqueue_item (root, item_type, item_uid, indexing_configuration, indexing_priority, changed) VALUES (?, ?, ?, ?, ?, ?)' with params ["1", "sys_file_metadata", 571, "sys_file_metadata", 0, 1567163284]: Field 'errors' doesn't have a default value`

MySQL error:
`[HY000][1364] Field 'errors' doesn't have a default value`

It's an issue in our environment running sql_mode "STRICT_TRANS_TABLES".

Adding an empty error string when doing INSERTs solves this problem.
- HMMH\\SolrFileIndexer\\IndexQueue\\FileInitializer
- HMMH\\SolrFileIndexer\\IndexQueue\\Queue

This would improve compatibility for strict mysql environments. Would be great if this improvement could get into the code.

Or it's an issue for the solr extension itself and the field tx_solr_indexqueue_item.errors should have a default value?

best wishes
Frank

**Comment by swilking** [comment]
We fix this problem and created a pull request for this issue: https://github.com/hmmh/typo3-solr-file-indexer/pull/15
In the next release this issue is solved.
