### ISSUE TITLE
Link/URL von gefundenen Dokumente ist "null"

### ISSUE THREAD

**Issue by gerchomat** [hmmh/typo3-solr-file-indexer#16]
Hi,

ich hab die Extension soeben installiert und es funktioniert alles sehr einfach und gut.
Allerdings ist der "Link" meines Suchergebnisses, also der Datei die gefunden wird "null".

TYPO3: 9.5.9
Solr: 9.0.2

**Comment by swilking** [comment]
Das Problem wurde analysiert. Fix für dieses Problem ist in https://github.com/hmmh/typo3-solr-file-indexer/pull/17 vorhanden und wird in die nächste Version einfließen.

**Comment by swilking** [comment]
gemergt
