### ISSUE TITLE
Nichtöffentliche Dokumente

### ISSUE THREAD

**Issue by Finulin** [hmmh/typo3-solr-file-indexer#18]
Dokumente die sich in Datensätzen befinden die nicht öffentlich sind, sollten nicht indiziert werden.
![fileadmin](https://user-images.githubusercontent.com/31020053/67744438-d2dbdd80-fa21-11e9-89e8-1e5a414a6324.png)

**Comment by swilking** [comment]
Wir werden das ggf. später einmal prüfen. In erster Linie ist es aber so, dass nur Dokumente indexiert werden, die in den Metadaten für die Indexierung freigegeben sind.

**Comment by christophlehmann** [comment]
Ich würde es nicht abhängig machen von diesem Flag, sondern es als weiteres Feld mit aufnehmen um darauf einen Filter anwenden zu können. Anwendungsbeispiel: Intranetsuche

**Comment by swilking** [comment]
v3 arbeitet mit File Collections, hier können individuelle Collections für verschiedene Seitenbäum definiert werden
