### ISSUE TITLE
Possible to update composer.json to "solr" extension in version 11?

### ISSUE THREAD

**Issue by hoermannklaus** [hmmh/typo3-solr-file-indexer#24]
I wondered if you tested using the extension with the "solr" extension in Version 11 also? Because only solr in version 11 is compatible with TYPO3 V10. How could you use typo3-solr-file-indexer in TYPO3 V10 then, if it is not compatible with "solr" in version 11, which is required for TYPO3 V10?

I was not able to update the extensions "solr" to v11 and "solr_file_indexer" to "dev-master" because it would say, that it need "solr" in version 9 or 10, which IMO does not make sense.

The missing dependency lies in the "composer.json" "require" section.

Thanks

**Comment by swilking** [comment]
Thank you for this information. We fixed the solr version number, v2.1.1 is compatible with EXT:solr v11

**Comment by hoermannklaus** [comment]
Great. Thanks for the quick change.
