### ISSUE TITLE
[Ask for feature] Indexing PDF content

### ISSUE THREAD

**Issue by UNI49** [hmmh/typo3-solr-file-indexer#25]
Hello,

Is there any possibilities to index content of PDF, like doing a pdftotext or something? There is nothing in the documentation for that purpose.

Thanks for help.

**Comment by swilking** [comment]
Hello,

yes of course. Apache Tika, which is capable of detecting and extracting metadata from approx. 1200 different file types is used for document content analysis. In the example configuration plugin.tx_solr.index.queue.sys_file_metadata.allowedFileTypes is pdf already included. Here you can specify the extension types to parse.
