### ISSUE TITLE
Error in upgrade wizard (TYPO3 9 to 10) in composer mode when typo3/cms-dashboard is not installed

### ISSUE THREAD

**Issue by sterborg** [hmmh/typo3-solr-file-indexer#26]
In composer mode without typo3/cms-dashboard installed the upgrade wizard throws an error that the dashboard is missing. typo3/cms-dashboard, however is not a requirement in ext_emconf.php and composer.json.
After the installation of typo3/cms-dashboard the error is gone.

**Comment by swilking** [comment]
Thank you, it is fixed in version 2.3.0
