### ISSUE TITLE
Declaration compatibility error for FileIndexer::itemToDocument

### ISSUE THREAD

**Issue by sterborg** [hmmh/typo3-solr-file-indexer#27]
Fatal error: Declaration of HMMH\SolrFileIndexer\Indexer\FileIndexer::itemToDocument(ApacheSolrForTypo3\Solr\IndexQueue\Item $item, $language = 0) 
must be compatible with 
ApacheSolrForTypo3\Solr\IndexQueue\Indexer::itemToDocument(ApacheSolrForTypo3\Solr\IndexQueue\Item $item, int $language = 0): ?ApacheSolrForTypo3\Solr\System\Solr\Document\Document
in .../public/typo3conf/ext/solr_file_indexer/Classes/Indexer/FileIndexer.php on line 50

TYPO3 10.4.16
solr 11.0.4
solr_file_indexer 2.2.0

**Comment by swilking** [comment]
Thank you for the issue. It is fixed in Version 2.3.0
