### ISSUE TITLE
must be compatible with ApacheSolrForTypo3

### ISSUE THREAD

**Issue by netengine-at** [hmmh/typo3-solr-file-indexer#29]
Hi,

today while manually indexing sys_file_metadata I came across the following error:

Fatal error: Declaration of HMMH\SolrFileIndexer\Indexer\FileIndexer::itemToDocument(ApacheSolrForTypo3\Solr\IndexQueue\Item $item, $language = 0) must be compatible with ApacheSolrForTypo3\Solr\IndexQueue\Indexer::itemToDocument(ApacheSolrForTypo3\Solr\IndexQueue\Item $item, int $language = 0): ?ApacheSolrForTypo3\Solr\System\Solr\Document\Document in /usr/www/users/feldkm/intranet_v9_feldkirch.at/typo3conf/ext/solr_file_indexer/Classes/Indexer/FileIndexer.php on line 103

Not sure what is going on here, everything was working a few days ago...

TYPO3 9.5.27
Extensions:
solr - 11.0.4
solr_file_indexer - 2.2.0
tika - 6.0.0

**Comment by netengine-at** [comment]
Hi, it seems it's solr 11.0.4 Extension with 11.0.3 everything works fine...

**Comment by swilking** [comment]
Please update solr_file_indexer to v2.3.1
There is a fix for Solr 11.0.4
