### ISSUE TITLE
Do not use $connection->errorInfo() for success

### ISSUE THREAD

**Issue by frommo** [hmmh/typo3-solr-file-indexer#33]
Hi,

we have the problem that the indexing task never successfully finishes because of Queue->addMultipleItemsToQueue() always returning false. The culprit is a check for errorInfo() being empty:

https://github.com/hmmh/typo3-solr-file-indexer/blob/master/Classes/IndexQueue/Queue.php#L103

This ist not true for our environment (MariaDB 10.3.28, PHP 7.4.22, mysqlnd), errorInfo() is something like ["000000", null, null] even if the query is successful. DBAL also has errorInfo() deprecated: https://github.com/doctrine/dbal/pull/4020

I suggest removing the check and replace it with only `return true;`. Should there really be a problem, an exception will be thrown anyway. Alternatively we could sum up all return values of `bulkInsert()` and compare it with `count($items)`, but I think this will not be necessary.

Kind regards,
Christian

**Comment by swilking** [comment]
#34

**Comment by swilking** [comment]
is fixed in 2.3.3

**Comment by frommo** [comment]
Thanks a lot for the quick fix, this is perfect!
