### ISSUE TITLE
[Question] show search results of files

### ISSUE THREAD

**Issue by Hobokens** [hmmh/typo3-solr-file-indexer#35]
Hi,
I'm using TYPO3 10.4.18, solr_file_indexer 2.3.3. and tika 6.0.
The indexing of files is perfect. Now I wonder whether it's possible to show search results inside files like you can do with pages.

Regards
Hobokens

**Comment by swilking** [comment]
Hi,
in the partial Result/Document of the EXT:solr you can get the content about the Document object. The content of the file ist saved in the property {document.content}. To switch the output between files and pages you ca ncheck the property {document.type}, which includes "pages" or "sys_file_metadata" (or something else like "tx_news_domain_model_news").

Best regards,
Sascha

**Comment by Hobokens** [comment]
Hi Sascha,

great, I've got it. Thanks for your help!
Have a nice weekend
Hobokens
