### ISSUE TITLE
Call to undefined method ApacheSolrForTypo3\Solr\Util::getSolrConfigurationFromPageId()

### ISSUE THREAD

**Issue by Solution97** [hmmh/typo3-solr-file-indexer#36]
Hi,
I tried to install your extension on my Typo3 v10 Web and I got the following error, when I add a document to the search index:
![image](https://user-images.githubusercontent.com/18093934/130597669-57d8fbfe-aea0-4077-91cc-d29719c02dac.png)

SOLR got serveral changes for supporting Typo3 v10. And one of this changes is causing my error. Have a look here: 
![image](https://user-images.githubusercontent.com/18093934/130597951-e2294210-2a1e-43ed-a9f2-7cf699eb18a1.png)
Commit: https://github.com/TYPO3-Solr/ext-solr/commit/03080d4d55eeb9d50b15348f445d23e57e34e461

Here my Versions:
apache-solr-for-typo3/solr -> 11.1.1
hmmh/solr-file-indexer -> 2.3.3
typo3/cms-core -> 10.4.20

Thanks in advance and have a nice day!

**Comment by swilking** [comment]
The current version from solr_file_indexer isn't compatible with EXT:solr 11.1.x, which was published on Aug 20, yet.

**Comment by Solution97** [comment]
Ahh ok  I understand, but than you have set your requierments wrong:
![image](https://user-images.githubusercontent.com/18093934/130608318-e7c4f40c-f064-4552-8443-60fdd20d373f.png)
![image](https://user-images.githubusercontent.com/18093934/130608430-d2118f63-c897-4790-aefe-8dc6d97b0374.png)

So if 1.1.x is not supported, you should change your requierment from ^11.0.4 to ~11.0.4:
![image](https://user-images.githubusercontent.com/18093934/130608536-28defe58-1a2c-4a1e-b779-c20cdd9e42a5.png)

I cant downgrade my SOLR, because I need latest features of it, so I wanted aks you kindly if its possible to make it compatible with EXT:solr 11.1.x

Thanks for your fast response!

**Comment by swilking** [comment]
fixed in version 2.3.5
