### ISSUE TITLE
Version compatibility with ext:solr 11.2.0

### ISSUE THREAD

**Issue by derhansen** [hmmh/typo3-solr-file-indexer#39]
Version constraints to ext:solr are currently defined with `^11.0.4, <11.2.0` preventing to use this extension together with the latest version of ext:solr for TYPO3 10.4. What is required to make this extension compatible with the latest version of ext:solr?

**Comment by swilking** [comment]
There are different return types in solr 11.2.x, see https://github.com/hmmh/typo3-solr-file-indexer/pull/38
We publish a new version as soon as possible.

**Comment by swilking** [comment]
we published a new version of the extension with solr 11.2.0 compatibility.
