### ISSUE TITLE
Errror GarbageCollector.php

### ISSUE THREAD

**Issue by Hobokens** [hmmh/typo3-solr-file-indexer#42]
Hi,

thanks for the new version. Testing it, I get the following error:

`Call to undefined method Doctrine\DBAL\Driver\Mysqli\MysqliStatement::fetchAssociative() | Error thrown in file /var/www/vhosts/xxxx.my-provider.de/httpdocs/typo3cms/abcd/typo3conf/ext/solr_file_indexer/Classes/Hook/GarbageCollector.php in line 138. Requested URL: https://www.my-domain.de/typo3/index.php?route=%%2Frecord%%2Fedit&token=--AnonymizedToken--&edit%%5Bsys_file_metadata%%5D%%5B4135%%5D=edit&returnUrl=%%2Ftypo3%%2Findex.php%%3Froute%%3D%%252Frecord%%252Fedit%%26token%%3Dc833f075aca63ae8d8693f2b7ed29a54f12e7098%%26edit%%255Btt_content%%255D%%255B4488%%255D%%3Dedit%%26returnUrl%%3D%%252Ftypo3%%252Findex.php%%253Froute%%253D%%25252Fmodule%%25252Fweb%%25252Flayout%%2526token%%253D32484cd02184272c1e04f4dce1e8595535a8c86f%%2526id%%253D1678%%2523element-tt_content-4488 `

TYPO3 10.4.31
Solr 11.2.
Tika 10.0.2
solr_file_indexer 2.5.0

**Comment by swilking** [comment]
Hmm, on my System it works fine. Which version has your doctrine/dbal package? We use 2.13.9 which use the forward compatibility layer. Can you update your doctrine/dbal package?

**Comment by Hobokens** [comment]
TYPO3 10.4.31 comes with `doctrine/dbal package 2.10. `
I don't have a composer installation. I have to check how to update `doctrine/dbal package`.

**Comment by swilking** [comment]
As alternative you can use the version 2.4.0 from solr_file_indexer which ist compatible with doctrine/dbal 2.10

**Comment by Hobokens** [comment]
Thanks, I will downgrade to version 2.4.0
