### ISSUE TITLE
Call to undefined method Doctrine\DBAL\Driver\Mysqli\MysqliStatement::fetchAssociative()

### ISSUE THREAD

**Issue by UBA-NE** [hmmh/typo3-solr-file-indexer#43]
Hi,

TYPO3: 10.4.31
solr_file_indexer: 2.5.0
PHP: 7.4.30

When deleting a file, I get the following error: 

> Call to undefined method Doctrine\DBAL\Driver\Mysqli\MysqliStatement::fetchAssociative()

../ext/solr_file_indexer/Classes/Hook/GarbageCollector.php
#184 fetchAssociative() 

when I replace the **fetchAssociative()** with **fetch()** the error is fixed.

![grafik](https://user-images.githubusercontent.com/6997013/194228635-6c0d3bc2-3798-4af6-bc02-73d327b38de5.png)

**Comment by swilking** [comment]
Take a look at https://github.com/hmmh/typo3-solr-file-indexer/issues/42, please

**Comment by swilking** [comment]
fixed in version 2.5.1
