### ISSUE TITLE
non visible documents

### ISSUE THREAD

**Issue by Hobokens** [hmmh/typo3-solr-file-indexer#49]
Hi,
Is there a way to not index files marked as not visible with solr_file_indexer?

TYPO3 11.24, solr_file_indexer 2.5.4
![non_visible_file](https://user-images.githubusercontent.com/6764582/228191537-e340d11e-3295-496c-9e4d-0d89e25c3c17.png)

**Comment by swilking** [comment]
Perhaps it is possible to set an additionalWhereClause like this:
plugin.tx_solr.index.queue.sys_file_metadata.additionalWhereClause = visible=1

Another way is to remove the document from search (remove checkbox in tab "Suche" from Siteroot)
