### ISSUE TITLE
[FEATURE] Re-index files, when folder has been renamed

### ISSUE THREAD

**Issue by derhansen** [hmmh/typo3-solr-file-indexer#53]
When a folder has been renamed, all files in the folder need to get reindexed, since the solr index still has contains the old (and invalid) path to the files.

The PSR-14 event `AfterFolderRenamedEvent` is a good candidate to use for this feature.

**Comment by swilking** [comment]
Thanks for your input. Which version of Solr file indexer are you using? v2.x or v3.x? v2 will only receive bugfixes, in v3 exists a new mode of file indexing with file collections where a scheduler task refresh the index.
