### ISSUE TITLE
Old Typo3 11 Task cannot unserialize during opening sheduler-Menu

### ISSUE THREAD

**Issue by hdietrich-timespin** [hmmh/typo3-solr-file-indexer#54]
I use typo3-solr-file-indexer  Version 3.0.0 with Typo3 12.4.10 and PHP 8.2 (DB-Data is comming from Typo3 11 Version)

If i open the sheduler-Menu i get this error: 

```
(1/1) TypeError
Cannot assign int to property HMMH\SolrFileIndexer\Task\DeleteByTypeTask::$reindexing of type bool
```

See: 
![grafik](https://github.com/hmmh/typo3-solr-file-indexer/assets/117842214/82c217da-3d26-464c-9f3d-1b6a75163ca1)

I think is a problem with unserialize old DB-string fom Typo3 11.

**Comment by swilking** [comment]
Please remove the task in the database

**Comment by hdietrich-timespin** [comment]
Ok. it works for me
