### ISSUE TITLE
item-queue-worker and large numbers of files

### ISSUE THREAD

**Issue by wkrawczak** [hmmh/typo3-solr-file-indexer#56]
Hi,

I have a project where we have about 60k files and growing. The item-queue-worker doesn't seem to be able to handle this or at least it doesn't work as expected.
We run it in Scheduler every couple of days, but it never finishes running. It starts at night and even when we check on it after a couple of days it still says "running". When running it from CLI it just sits there as well, no errors. So it is most likely processing or it just hangs at some point, because it never processes all files.

Do you have a solution for this kind of situation?

Thanks,

Wojtek

Versions info:
TYPO3 12.4.13
solr_file_indexer 3.0.0
solr 12.0.2
PHP 8.2.22

**Comment by swilking** [comment]
We have a project with approximately 20k files. The task runs smoothly here in about 5-7 minutes. Are there any error messages in the PHP error.log (memory_limit or something else)? How many entries are in the 'tx_solrfileindexer_items' table? Does it always stop at the same file?

**Comment by wkrawczak** [comment]
The error.log is clean - the script also doesn't end (the behavior I usually see when it hits a limit / critical error), so it's very strange. For example today it started at 3:10 AM and it's still in "Running" state in the Scheduler backend overview.
The 'tx_solrfileindexer_items' has 119316 entries (a lot of these files are available in a secondary language).

How could I find out on which file it stops?

Thanks!

**Comment by swilking** [comment]
You can truncate the table and start the job again, then you can see which items are stored in the table, the last one with the highest uid show you the UID from sys_file_metadata (item_uid). In the sys_file_metadata the file UID is stored. In the filelist you can search for the file, the next one in the list could be the file which makes trouble.

**Comment by swilking** [comment]
In versions 3.0.1 and 4.0.0, the initialization tasks can optionally be split per Collection UID to divide very large collections into multiple smaller collections.
